# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  CLUSTERNAME: 'stackfile-lab'
  REGISTRYNAME: 'stackfile-registry'
  REGISTRYIMAGE: 'registry:3'
  DOCKERNETWORK: 'kind'

tasks:
  start-registry:
    desc: Start local docker.io mirror registry for development environment
    status:
      - docker ps -q -f name={{.REGISTRYNAME}} | grep -q .
    cmds:
      - docker run --name {{.REGISTRYNAME}} -e REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io -e OTEL_TRACES_EXPORTER=none -e REGISTRY_LOG_LEVEL=info --network {{.DOCKERNETWORK}} --restart unless-stopped --detach {{.REGISTRYIMAGE}} 
  start-cluster:
    desc: Start Kind cluster for development environment
    aliases: ['up']
    status:
      - kind get clusters | grep {{.CLUSTERNAME}}
    cmds:
      - |
        cat <<EOT | kind create cluster --name {{.CLUSTERNAME}} --config=-
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        nodes:
          - role: control-plane
          - role: worker
          - role: worker
        networking:
          kubeProxyMode: "nftables"
        containerdConfigPatches:
          - |-
            [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
              [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
                endpoint = ["http://{{.REGISTRYNAME}}:5000"]
        EOT
      - task: start-registry
  destroy-registry:
    desc: Destroy local docker.io mirror registry for development environment
    cmds:
      - docker rm --force --volumes {{.REGISTRYNAME}}
  destroy-cluster:
    desc: Destroy Kind cluster for development environment
    cmds:
      - kind delete cluster --name {{.CLUSTERNAME}}
  recreate:
    desc: Recreate development environment
    cmds:
      - task: destroy-cluster
      - task: start-cluster
  destroy:
    desc: Destroy development environment
    aliases: ['down']
    cmds:
      - task: destroy-cluster
      - task: destroy-registry
