apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: monitoring
  namespace: flux-system
  labels:
    appset: "true"
spec:
  type: Static
  defaultValues:
    namespace:
      name: "monitoring"
      labels:
        gateway-api: "private"
---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: empty
  namespace: flux-system
  labels:
    appset: "true"
spec:
  type: Static
  defaultValues:
    namespace:
      name: "empty"
---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: envoy-gateway-system
  namespace: flux-system
  labels:
    appset: "true"
spec:
  type: Static
  defaultValues:
    namespace:
      name: "envoy-gateway-system"
    repositories:
      - name: envoy-gateway-system
        url: oci://docker.io/envoyproxy
        type: oci
        interval: 24h
    releases:
      - name: envoy-gateway-system
        chart: gateway-helm
        version: v1.5.0
        repository: envoy-gateway-system
---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: kube-system
  namespace: flux-system
  labels:
    appset: "true"
spec:
  type: Static
  defaultValues:
    namespace:
      name: "kube-system"
      labels:
        gateway-api: "public"
    repositories:
      - name: metrics-server
        url: https://kubernetes-sigs.github.io/metrics-server/
        type: default
        interval: 24h
---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: redis
  namespace: flux-system
  labels:
    appset: "true"
spec:
  type: Static
  defaultValues:
    namespace:
      name: "redis"
      labels:
        gateway-api: "private"
    repositories:
      - name: bitnami
        url: oci://registry-1.docker.io/bitnamicharts
        type: oci
        interval: 24h
    releases:
      - name: redis
        chart: redis
        version: 24.1.0
        repository: bitnami
